channels:
  - base
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - bcbiogff==0.6.4
#  - bcftools==1.6-0
  - bcftools
  - bioconductor-biobase==2.38.0
  - bioconductor-biocgenerics==0.24.0
  - bioconductor-biocparallel==1.12.0
  - bioconductor-biostrings==2.46.0
  - bioconductor-delayedarray==0.4.1
  - bioconductor-genomeinfodb==1.14.0
  - bioconductor-genomeinfodbdata==1.0.0
  - bioconductor-genomicalignments==1.14.0
  - bioconductor-genomicranges==1.30.0
  - bioconductor-iranges==2.12.0
  - bioconductor-rsamtools==1.30.0
  - bioconductor-rtracklayer==1.38.0
  - bioconductor-s4vectors==0.16.0
  - bioconductor-summarizedexperiment==1.8.0
  - bioconductor-xvector==0.18.0
  - bioconductor-zlibbioc==1.24.0
  - biopython==1.70
  - bzip2==1.0.6
  - ca-certificates==2018.1.18
  - cairo==1.14.6
  - certifi==2018.1.18
#  - curl==7.54.1
  - curl
  - distance==0.1.3
  - fontconfig==2.12.1
  - freetype==2.7
  - gettext==0.19.8.1
  - glib==2.51.4
  - gmp==6.1.2
  - graphite2==1.3.11
  - gsl==2.1
  - harfbuzz==1.4.3
  - htslib==1.5-0
  - icu=58.2
  - intel-openmp==2018.0.0
  - java-jdk==8.0.92
  - jpeg==9b
  - krb5==1.14.2
  - libffi==3.2.1
#  - libgcc==7.2.0
#  - libgcc-ng==7.2.0
  - libgcc
  - libgcc-ng
  - libgfortran-ng==7.2.0
  - libiconv==1.15
  - libpng==1.6.28
  - libssh2==1.8.0
  - libstdcxx-ng==7.2.0
  - libtiff==4.0.7
  - libuuid==1.0.3
  - libxcb==1.12
  - libxml2==2.9.5
  - make==4.2.1
  - mkl==2018.0.1
  - mmtf-python==1.0.2
  - mpfr==3.1.5
  - msgpack-python==0.5.5
  - ncurses==5.9
  - nextgenmap==0.4.13
  - numpy==1.12.1
  - olefile==0.45.1
  - openjdk==8.0.121
#  - openssl==1.0.2n
  - openssl
  - pandoc==2.0.0.1
  - pango==1.40.4
  - pcre==8.39
  - perl==5.22.2.1
  - picard==1.141
  - pillow==4.3.0
  - pip==9.0.1
  - pixman==0.34.0
#  - pysam==0.12.0.1
  - pysam
  - python==2.7.14
  - r-akima==0.6_2
  - r-backports==1.0.5
  - r-base==3.4.1
  - r-base64enc==0.1_3
  - r-bh==1.65.0_1
  - r-bitops==1.0_6
  - r-data.table==1.10.4
  - r-digest==0.6.12
  - r-evaluate==0.10.1
  - r-futile.logger==1.4.3
  - r-futile.options==1.0.0
  - r-glue==1.1.1
  - r-gwpcr==0.9.9
  - r-highr>=0.6
  - r-htmltools==0.3.6
  - r-jsonlite==1.5
  - r-knitr==1.16
  - r-lambda.r==1.1.9
  - r-lattice==0.20_34
  - r-magrittr==1.5
  - r-markdown==0.8
  - r-matrix==1.2_7.1
  - r-matrixstats==0.52.2
  - r-mime==0.5
  - r-rcpp==0.12.13
  - r-rcurl==1.95_4.8
  - r-rmarkdown==1.8
  - r-rprojroot==1.2
  - r-snow==0.4_2
  - r-sp==1.2_7
  - r-statmod==1.4.30
  - r-stringi==1.1.6
  - r-stringr==1.3.0
  - r-xml==3.98_1.6
  - r-yaml==2.1.14
  - readline==6.2
  - recordtype>=1.1
  - regex==2016.06.24
  - reportlab==3.4.0
  - samtools==1.5
  - setuptools==38.5.2
  - six==1.11.0
  - sqlite==3.13.0
  - tk==8.5.19
  - trimmomatic==0.33
#  - wget==1.18
  - wget>=1.21.0
  - wheel==0.30.0
  - xorg-kbproto==1.0.7
  - xorg-libice==1.0.9
#  - xorg-libs1.2.2
  - xorg-libx11==1.6.4
  - xorg-libxau==1.0.8
  - xorg-libxdmcp==1.1.2
  - xorg-libxext==1.3.3
  - xorg-libxrender==0.9.10
  - xorg-renderproto==0.11.1
  - xorg-xextproto==7.3.0
  - xorg-xproto==7.0.31
  - xz==5.2.3
  - zlib==1.2.8
