channels:
  - base
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - bcbiogff
  - bcftools
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - bioconductor-biocparallel
  - bioconductor-biostrings
  - bioconductor-delayedarray
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - biopython
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - curl
  - distance
  - fontconfig
  - freetype
  - gettext
  - glib
  - gmp
  - graphite2
  - gsl
  - harfbuzz
  - htslib
  - icu
  - intel-openmp
  - java-jdk
  - jpeg
  - krb5
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - make
  - mkl
  - mmtf-python
  - mpfr
  - msgpack-python
  - ncurses
  - nextgenmap
  - numpy
  - olefile
  - openjdk
  - openssl
  - pandoc
  - pango
  - pcre
  - perl
  - picard
  - pillow
  - pip
  - pixman
  - pysam
  - python==2.7.14
  - r-akima==0.6_2
  - r-backports==1.0.5
  - r-base==4.1.3
  - r-base64enc
  - r-bh
  - r-bitops
  - r-data.table
  - r-digest
  - r-evaluate
  - r-futile.logger
  - r-futile.options
  - r-glue
  - r-gwpcr
  - r-highr
  - r-htmltools
  - r-jsonlite
  - r-knitr
  - r-lambda.r
  - r-lattice
  - r-magrittr
  - r-markdown
  - r-matrix
  - r-matrixstats
  - r-mime
  - r-rcpp
  - r-rcurl
  - r-rmarkdown
  - r-rprojroot
  - r-snow
  - r-sp
  - r-statmod
  - r-stringi
  - r-stringr
#for pdf rendering
  - r-tinytex==0.39
  - r-xml
  - r-yaml
  - readline
  - recordtype
  - regex 
  - reportlab==3.4
  - samtools
  - setuptools
  - six
  - sqlite
#for pdf rendering
#  - texlive-core
  - tk
  - trimmomatic
  - wget
  - wheel
  - xz
  - zlib
