channels:
  - base
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - bcbiogff
  - bcftools
  - bioconductor-rtracklayer
  - biopython
  - curl
  - distance
  - fontconfig
  - freetype
  - gettext
  - glib
  - gmp
  - graphite2
  - gsl
  - harfbuzz
  - htslib
  - icu
  - intel-openmp
  - java-jdk
  - make
  - mkl
  - mmtf-python
  - mpfr
  - msgpack-python
  - ncurses
  - nextgenmap
  - numpy
  - olefile
  - openjdk
  - openssl
  - pandoc
  - pango
  - pcre
  - perl
  - picard
  - pillow
  - pip
  - pixman
  - pysam
  - python
  - r-base
  - r-data.table
  - r-gwpcr
  - r-knitr
  - r-markdown
  - r-rmarkdown
#for pdf rendering
  - r-tinytex==0.39
  - readline
  - recordtype
  - regex 
  - reportlab
  - samtools
  - setuptools
  - six
  - sqlite
#for pdf rendering
#  - texlive-core
  - tk
  - trimmomatic
  - wget
  - wheel
  - xz
  - zlib
